modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Chaos-Awakens-Mod-Team/ChaosAwakens/issues"
displayURL=""
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="chaosawakens"
version="${file.jarVersion}"
displayName="Chaos Awakens"
description='''A successor mod that brings OreSpawn content into newer Minecraft versions.'''
itemIcon="chaosawakens:ultimate_pickaxe"
configBackground="chaosawakens:textures/block/gate_block.png"

[[dependencies.chaosawakens]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.chaosawakens]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17]"
ordering="NONE"
side="BOTH"

[[dependencies.chaosawakens]]
modId="geckolib3"
mandatory=true
versionRange="[3.0,)"
ordering="NONE"
side="BOTH"
